### ISSUE TITLE
使用时会突然报错...

### ISSUE THREAD

**Issue by uniteweiwei** [jesusslim/mqttclient#2]
![image](https://user-images.githubusercontent.com/19373139/58024345-8b812500-7b44-11e9-8aa9-6a19a5e13400.png)
报错信息如上图所示,是用swoole不行么,监听有相关参考代码么,大大

**Comment by jesusslim** [comment]
你这个错误可能是mqtt没连上或者已经断开了

**Comment by uniteweiwei** [comment]
要是在这里做try catch的话,会不会好一点?至少不能抛出fatal error哦....

**Comment by uniteweiwei** [comment]
我们用supervisor监听了这个简称,崩掉之后,再次重启,但是会有一些设备还是无法连接

**Comment by uniteweiwei** [comment]
进程

**Comment by jesusslim** [comment]
因为按照之前swoole的文档 send失败是不会抛错的 只会返回false并设置socket->errCode 可能是swoole不同版本的差异引起的 为避免此类问题目前已做捕获处理 可将本mqttclient库更新到1.52版本
另外这边不建议使用swoole版本的mqttclient是因为swoole的client一直存在分包问题没有解决https://github.com/swoole/swoole-src/issues/2030
消息量大的话推荐是使用mosquitto的版本

**Comment by uniteweiwei** [comment]
好的,谢谢你
