### ISSUE TITLE
请问有方法释放内存么,内存占用1天增加7%

### ISSUE THREAD

**Issue by uniteweiwei** [jesusslim/mqttclient#3]
![image](https://user-images.githubusercontent.com/19373139/58467578-905e5e00-816e-11e9-83cc-4c471e99d1d9.png)
4g的内存,这情况的话,基本上3天就得重启一次
![image](https://user-images.githubusercontent.com/19373139/58467745-cef41880-816e-11e9-89b5-a45a804220f5.png)
调用代码如下:
`  
public function handle()
{
        $server = config('mqtt.host');     
        $port = config('mqtt.port');                     
        $username = config('mqtt.username');                
        $password = config('mqtt.password');                   
        $client_id = "backendService"; 
        ini_set('memory_limit', '-1');

        $client = new Client($server, $port, $client_id);
        $client->setMqttVersion(MqttVersion::V311);
        $client->setAuth($username, $password);
        $client->setKeepAlive(60);
        $client->setStore(new Store());
        $client->setLogger(new Logger());
        $client->setMaxReconnectTimesWhenError(0);
        $client->setPackageMaxLength(1024*1024*256);

        $client->setTopics([
            new Topic('$sys/client/connect', function ($msg) {
                $this->clientConnect($msg);
            }, 1),

            new Topic('$sys/client/disconnect', function ($msg) {
                $this->clientDisconnect($msg);
            }, 1),

            new Topic('$sys/app/callback', function ($msg) use ($client) {
                $this->orderCallback($msg, $client);
            }, 0),
        ]);

        $client->setTimer(1000, function ($timer_id, $mqtt) {
            $this->publishOrderStartData($mqtt);
        });

        $client->setTimer(1100, function ($timer_id, $mqtt) {
            $this->publishOrderStopData($mqtt);
        });

        $client->setTimer(1, function ($timer_id, $mqtt) use ($client) {
            $client->on(ClientTriggers::SOCKET_FIRST_CLOSE, function () use ($client) {
                $this->resetAllDevice();
                Cache::forever('mqtt_server_is_connected', false);
                Log::debug('mqtt_server_is_connected', [cache('mqtt_server_is_connected')]);
            });
            $client->on(ClientTriggers::RECEIVE_CONNACK, function () use ($client) {
                Cache::forever('mqtt_server_is_connected', true);
                Log::debug('mqtt_server_is_connected', [cache('mqtt_server_is_connected')]);
            });
            $client->on(ClientTriggers::DISCONNECT, function () use ($client) {
                Cache::forever('mqtt_server_is_connected', false);
                Log::debug('mqtt_server_is_connected', [cache('mqtt_server_is_connected')]);
            });
            $client->on(ClientTriggers::RECEIVE_PINGRESP, function () {
                Cache::forever('mqtt_server_is_connected', true);
            });
        });

        $client->connect();
    }`

**Comment by jesusslim** [comment]
我这边没有遇到过类似的问题 光看这些代码片段我也找不出问题 建议你多打一些日志调试一下 排查看看内存的增长具体是出现在哪段代码  例如单独跑你的订阅和轮询 看下内存增长 或是将业务逻辑简化例如改成最简单的输出 观察内存增长情况以排除业务逻辑问题
